# Generated by Django 3.2.8 on 2021-11-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=50, verbose_name='Nombre')),
                ('cif_proveedor', models.CharField(max_length=15, verbose_name='CIF')),
                ('domicilio_proveedor', models.CharField(max_length=50, verbose_name='Domicilio')),
                ('tel_proveedor', models.CharField(max_length=10, verbose_name='Telefono')),
                ('mail_proveedor', models.EmailField(max_length=254, verbose_name='Email')),
                ('estado_proveedor', models.BooleanField(default=True, verbose_name='activo')),
                ('logo_proveedor', models.ImageField(blank=True, null=True, upload_to='proveedores_logos', verbose_name='Logo')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
