# Generated by Django 3.2.8 on 2021-11-06 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50, verbose_name='Nombre')),
                ('imagen_producto', models.ImageField(blank=True, null=True, upload_to='productos_imagenes', verbose_name='Imagen')),
                ('descripcion_producto', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('precio_producto', models.FloatField(verbose_name='Precio')),
                ('disponible_producto', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedores')),
            ],
        ),
    ]
