# Generated by Django 3.2.8 on 2021-11-13 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_alter_estadospedidos_nombre_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadospedidos',
            name='id_deposito',
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_deposito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.deposito'),
        ),
    ]
