# Generated by Django 3.2.8 on 2021-11-13 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0005_auto_20211113_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='id_producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proveedores.producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedores'),
        ),
    ]
