# Generated by Django 3.2.8 on 2021-11-13 16:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0007_alter_pedido_id_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 11, 13, 16, 21, 35, 637509, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='cant_pedida',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='idproducto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proveedores.producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='numeroPedido',
            field=models.IntegerField(default=1, verbose_name='Número de Pedido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='valor_producto',
            field=models.FloatField(default=1, max_length=20, verbose_name='Valor Unitario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='valor_producto_total',
            field=models.FloatField(default=1, max_length=20, verbose_name='Valor Total'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.producto'),
        ),
    ]
