# Generated by Django 3.2.8 on 2021-11-19 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0010_auto_20211119_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='id_producto',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.estadospedidos'),
        ),
        migrations.AlterField(
            model_name='pedidodetalle',
            name='numeroPedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.pedido', verbose_name='Número de Pedido'),
        ),
    ]
