# Generated by Django 3.2.8 on 2021-11-20 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0011_auto_20211119_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='id_proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedores'),
            preserve_default=False,
        ),
    ]
