# Generated by Django 3.2.8 on 2021-11-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0012_pedido_id_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposito',
            name='es_predefinido',
            field=models.BooleanField(default=False),
        ),
    ]
