# Generated by Django 3.2.8 on 2021-11-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0013_deposito_es_predefinido'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposito',
            name='domicilio_deposito',
            field=models.CharField(default='Calle Santa Gema 3, fuengirola, Málaga', max_length=50, verbose_name='Domicilio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deposito',
            name='telefono_deposito',
            field=models.CharField(default=632782597, max_length=12, verbose_name='Telefono'),
            preserve_default=False,
        ),
    ]
